name: "tests feature combinations"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    name: cargo build/test ${{ matrix.features }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "-F mysql"]
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo build ${{ matrix.features }}
    - run: cargo test ${{ matrix.features }}
