name: "Check"
on:
- push
- workflow_dispatch
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.3.4
    - run: nix --experimental-features "nix-command flakes" flake check
