name: "Check"
on:
- push
- workflow_dispatch
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix --experimental-features "nix-command flakes" flake check -L
